Command: ninja flash
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/chris/.espressif/python_env/idf5.5_py3.12_env/lib/python3.12/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/chris/.espressif/python_env/idf5.5_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 1365, in _main
    main()
  File "/home/chris/.espressif/python_env/idf5.5_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 815, in main
    esp = esp or get_default_connected_device(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/.espressif/python_env/idf5.5_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 1246, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/home/chris/.espressif/python_env/idf5.5_py3.12_env/lib/python3.12/site-packages/esptool/loader.py", line 771, in connect
    last_error = self._connect_attempt(reset_strategy, mode)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/.espressif/python_env/idf5.5_py3.12_env/lib/python3.12/site-packages/esptool/loader.py", line 647, in _connect_attempt
    reset_strategy()  # Reset the chip to bootloader (download mode)
    ^^^^^^^^^^^^^^^^
  File "/home/chris/.espressif/python_env/idf5.5_py3.12_env/lib/python3.12/site-packages/esptool/reset.py", line 46, in __call__
    self.port.open()
  File "/home/chris/.espressif/python_env/idf5.5_py3.12_env/lib/python3.12/site-packages/serial/serialposix.py", line 338, in open
    self._update_rts_state()
  File "/home/chris/.espressif/python_env/idf5.5_py3.12_env/lib/python3.12/site-packages/serial/serialposix.py", line 708, in _update_rts_state
    fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_RTS_str)
OSError: [Errno 71] Protocol error
CMake Error at run_serial_tool.cmake:67 (message):
  
  /home/chris/.espressif/python_env/idf5.5_py3.12_env/bin/python;;/home/chris/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s3
  failed.



